<?php

namespace App\Http\Requests\User\Index;

use App\Http\Requests\BaseRequest;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Contracts\Validation\Validator;

class ProjectRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return  [
            'project_name' => ['required', 'min:1', 'max:254'],
            'investor' => ['required', 'min:1', 'max:254'],
            'address' => 'required|min:1|max:255',
            'pr_province' => 'required|exists:province,id',
            'pr_district' => 'required|exists:district,id',
            'pr_ward' => 'required|exists:ward,id',
        ];
    }

    public function failedValidation(Validator $validator)
    {
        session()->flash('popup', '#project_request');
        Toastr::error('Yêu cầu dự án không thành công!');
        parent::failedValidation($validator); // TODO: Change the autogenerated stub

    }
}
