<?php
return [
    'home' => [
      'num_paginate' => 20,
    ],
    'validate_message' => [
        'required' => ':attribute không được bỏ trống',
        'required_if' => ':attribute là bắt buộc khi :other là :value.',
        'alpha_num' => ':attribute chỉ chứa chữ cái và số',
        'unique' => ':attribute đã tồn tại',
        'min' => ':attribute chứa tối thiểu :min ký tự',
        'max' => [
            'numeric' => ':attribute không được lớn hơn :max.',
            'file' => ':attribute không được lớn hơn :max kilobytes.',
            'string' => ':attribute không được lớn hơn :max kí tự.',
            'array' => ':attribute không được nhiều hơn :max mục.',
        ],
    
        // 'file.max' => ':attribute không được lớn hơn :max kilobytes',
        'alpha' => ':attribute chỉ chứa chữ cái',
        'same' => ':attribute không khớp',
        'exists' => ':attribute không hợp lệ',
        'numeric' => ':attribute chỉ chứa số',
        'between' => [
            'numeric' => ':attribute phải từ :min - :max',
            'file' => ':attribute phải từ :min - :max kb',
            'string' => ':attribute phải từ :min - :max ký tự',
            'array' => ':attribute phải từ :min - :max phần tử',
        ],
        'array' => ':attribute không hợp lệ',
        'regex' => ':attribute không hợp lệ',
        'integer' =>':attribute chỉ chứa số nguyên',
        'gte' => [
            'numeric' => ':attribute phải lớn hơn hoặc bằng :value',
            'file' => ':attribute phải lớn hơn hoặc bằng :value kb',
            'string' => ':attribute phải lớn hơn hoặc bằng :value ký tự',
            'array' => ':attribute phải chứa :value phần tử hoặc hơn',
        ],
        'before' => ':attribute phải bé hơn ngày hiện tại',
        'after' => ':attribute phải lớn hơn :date',
        'after_or_equal' => ':attribute phải lớn hơn hoặc bằng :date',
        'confirmed' => 'nhập lại :attribute phải trùng khớp với :attribute',
        'required_without' => ':attribute không được bỏ trống',
        'url' => ':attribute phải là một url hợp lệ.',
        'date' => ':attribute không phải là ngày hợp lệ.',
        'email' => ':attribute phải là một địa chỉ email hợp lệ.',
    ],
    'validate_attribute_alias' => [
        'username' => 'tên đăng nhập',
        'fullname' => 'tên hiển thị',
        'password' => 'mật khẩu',
        're_password' => 'mật khẩu',
        'phone_number' => 'số điện thoại',
        'email' => 'email',
        'birthday' => 'ngày sinh',
        'personal_id' => 'số cmnd',
        'tax_number' => 'mã số thuế',
        'province' => 'tỉnh/thành phố',
        'district' => 'quận/huyện',
        'ward' => 'phường/xã',
        'source' => 'nguồn',
        'title' => 'tiêu đề',

        // personal
        'content_post' => 'nội dung',
        'upload-license' => 'giấy phép kinh doanh',
        // classified
        'description' => 'mô tả',
        'area' => 'diện tích',
        'juridical' => 'pháp lý',
        'gallery' => 'hình ảnh',
        'category' => 'mô hình',

        // project
        'project' => 'dự án',
        'projects' => 'dự án',
        'project_name' => 'tên dự án',
        'group_id' => 'mô hình',
        'investor' => 'chủ đầu tư',
        'project_description' => 'mô tả',
        'project_content' => 'tổng quan dự án',
        'project_url' => 'đường đẫn thân thiện',
        'location_descritpion' => 'vị trí',
        'utility_description' => 'tiện ích',
        'ground_description' => 'mặt bằng',
        'legal_description' => 'pháp lý',
        'payment_description' => 'thanh toán',
        'project_area_from' => 'diện tích nhỏ nhất',
        'project_area_to' => 'diện tích lớn nhất',
        'project_scale' => 'quy mô',
        'price' => 'giá bán',
        'unit_price' => 'đơn vị',
        'project_price' => 'giá bán trung bình',
        'project_rent_price' => 'giá mua trung bình',
        'project_direction' => 'hướng',
        'project_juridical' => 'pháp lý',
        'project_progress' => 'tình trạng',
        'project_furniture' => 'nội thất',
        'project_road' => 'chiều rộng đường',
        'bank_sponsor' => 'ngân hàng bảo trợ',
        'prepay_percent' => 'phần trăm trả trước',
        'loan_time' => 'thời gian vay',
        'interest_percent' => 'lãi suất',
        'video' => 'video',
        'video_url' => 'đường dẫn video',
        'meta_title' => 'tiêu đề dự án',
        'meta_key' => 'từ khóa trên công cụ tìm kiếm',
        'meta_desc' => 'mô tả trên công cụ tìm kiếm',
        'map_latitude' => 'vị trí',
        'map_longtitude' => 'vị trí',
        'province_id' => 'tỉnh / thành phố',
        'district_id' => 'quận / huyện',
        'ward_id' => 'phường / xã',
        'address' => 'địa chỉ',
        'image_thumbnail' => 'ảnh thumbnail',
        'image_url' => 'hình ảnh',

        // rank - cấp bậc
        'level_name' => 'tên cấp bậc',
        'percent_special' =>  'phần trăm ưu đãi',
        'classified_min_quantity' =>  'số tin tối thiểu',
        'classified_max_quantity' =>  'số tin tối đa',
        'deposit_min_amount' =>  'số tiền nạp tối thiểu',
        'deposit_max_amount' =>  'số tiền nạp tối đa',
        // danh sách chặn cấm
        'forbidden_word' => 'từ cấm',

        // comment
        'comment_content' => 'nội dung',
        'content' => 'nội dung',
        'content_comment' => 'nội dung',

        // banner
        'banner_group' => 'nhóm banner',
        'banner_group_name' => 'tên nhóm banner',
        'banner_permission' => 'cho phép quảng cáo',
        'banner_type' => 'kiểu banner',
        'banner_name' => 'tên banner',
        'banner_position' => 'vị trí',
        'banner_description' => 'mô tả',
        'banner_width' => 'chiều rộng',
        'banner_height' => 'chiều cao',
        'banner_coin_price' => 'số coin',
        'banner_price' => 'số tiền',

        // banner group
        'banner_group_id' => 'nhóm banner',
        'banner_title' => 'tiêu đề banner',

        // event
        'event_title' => 'tiêu đề sự kiện',
        'take_place' => 'địa điểm diễn ra',
        'start_date' => 'ngày diễn ra',
        'start_time' => 'thời gian diễn ra',
        'event_content' => 'nội dung sự kiện',
        'image_header_url' => 'ảnh bìa',
        'image_invitation_url' => 'ảnh thư mời',
        'event_url' => 'đường dẫn sự kiện',


        'amount_express' => 'số tiền nạp',
        'username_express' => 'tài khoản',

        'new_password' => 'mật khẩu mới',
        'current_password' => 'mật khẩu hiện tại',
        'deposit_code' => 'mã giao dịch',
        'deposit_type' => 'loại giao dịch',
        'banner_code' =>  'mã html',
        'pr_province' => 'tỉnh/thành phố',
        'pr_district' => 'quận/huyện',
        'pr_ward' => 'phường/xã',
        'company_name' => 'tên công ty',
        'progress' => 'tình trạng',
        'furniture' => 'nội thất',
        'paradigm' => 'mô hình',
        'paradigm_id' => 'mô hình',
        'deposit' => 'cọc trước',
        'capacity' => 'số người ở tối đa',
        'content' => 'nội dung',
        'g-recaptcha-response' => 'captcha',

        'template_name' => 'tiêu đề',
        'template_content' => 'nội dung',
        'job' => 'nghề nghiệp',
        'status' => 'trạng thái',
        'views' => 'lượt xem',
        'target_type' => 'loại',
        'is_active' => 'tình trạng',

        // mail
        'mail_host' => 'smtp', 
        'mail_port' => 'cổng',
        'mail_header' => 'tiêu đề',
        'mail_content' => 'nội dung',
        'mail_username' => 'tên đăng nhập',
        'mail_password' => 'mật khẩu',
        'user_mail' => 'email người nhận',
        'mail_encription' => 'mã hóa',
        // mail campaign
        'campaign_name' => 'tên chiến dịch',
        'mail_template_id' => 'mẫu mail',
        'cus_status'=> 'tình trạng',
        'cus_source'=> 'nguồn',
        'cus_job'=> 'nghề nghiệp',
        'date_from'=> 'thời gian',
        'date_to'=> 'thời gian',
        'start_date'=> 'ngày gửi',
        'customer'=> 'email hoặc tên',
        'customers'=> 'khách hàng',

        // guest contact
        'contact_name' => 'tên',
        'contact_email' => 'email',
        'contact_phone' => 'số điện thoại',
        'contact_address' => 'địa chỉ',

        // report
        'report_type' => 'loại báo cáo',
        'report_content' => 'mô tả',

        // seo
        'seo.meta_key' => 'từ khóa',
        'seo.meta_title' => 'tiêu đề',
        'seo.meta_description' => 'mô tả',

        // chat
        'chat_type' => 'mục hỗ trợ',
        'message' => 'tin nhắn',

        // mail template
        'template_title' => 'tiêu đề ',
        'template_mail_title' => 'tiêu đề mail',
        'template_action' => 'tên action',

        'num_use' => 'số lần dùng tối đa',
        'value' => 'phần trăm áp dụng',
        'news_description' => 'mô tả ngắn',
        'news_title' => 'tiêu đề',
        'news_content' => 'nội dung',
    ]
];
